### ISSUE TITLE
Crash when using desync tool

### ISSUE THREAD

**Issue by Piratux** [Hornwitser/factorio_tools#2]
I've used the desync tool to analyze desync report, but it crashed after around a minute with the following command and following error:

```
C:\Users\HP\Desktop\Random_folder\Desync lab\factorio_tools-master>py -m hornwitser.factorio_tools desync desync-report-2023-02-12_23-14-50.zip > diff.txt
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\HP\Desktop\Random_folder\Desync lab\factorio_tools-master\hornwitser\factorio_tools\__main__.py", line 124, in <module>
    main()
  File "C:\Users\HP\Desktop\Random_folder\Desync lab\factorio_tools-master\hornwitser\factorio_tools\__main__.py", line 41, in main
    args.func(args)
  File "C:\Users\HP\Desktop\Random_folder\Desync lab\factorio_tools-master\hornwitser\factorio_tools\desync.py", line 296, in analyze
    diff_tagged_files(ref_files['level_with_tags'], des_files['level_with_tags'])
  File "C:\Users\HP\Desktop\Random_folder\Desync lab\factorio_tools-master\hornwitser\factorio_tools\desync.py", line 258, in diff_tagged_files
    print(token_path(b_chunk[j1]))
IndexError: list index out of range
```
The python version I'm using is 3.9.5
Here is the link to the desync zip file: https://drive.google.com/file/d/1IRTA9N3lrH29uSN06B05q8kjURR9yCjo/view?usp=sharing

**Comment by Hornwitser** [comment]
Thanks for the report, this has been fixed in v0.0.6.
